### ISSUE TITLE
원활한 문서 개발을 위해 커뮤니티 정책이 필요합니다

### ISSUE THREAD

**Issue by DevKang** [DeveloperAcademy-POSTECH/pos-frameworks-dictionary#1]
# 왜 이슈를 올렸는지
단순 코드가 아니라 문서를 리포지토리로 관리하는 것도 익숙하지 않지만, 많은 사람들이 공동으로 작업하는 오픈소스 운영 경험도 부족합니다. 
이 리포지토리를 어떤 정책으로 운영하면 좋을지 한번 이야기를 나눠보면 어떨까요?

**Comment by DevKang** [comment]
개인적으로 논의되었으면 하는 것들
    1. 이슈 발행을 위한 템플릿
    2. 메인테이너가 필요할 것인가?
    3. 기여를 원하는 사람들을 위한 가이드 문서(포크는 어떻게 하는지, 어떤 식으로 리뷰과정을 거쳐서 메인으로 병합할 것인지 등등)
    4. Discussion, Project 등 깃헙에서 제공되는 도구들을 사용하면 좋을지

**Comment by garlicvread** [comment]
커밋 메시지만 잘 써도 상당 부분 이해가 되는 것은 맞는데, 주석도 필요한 때가 있는 것 같습니다. 또, 주석 양식을 맞춰서 많이 작성하는 것 같습니다. 주석이나 README.md파일 작성방법 등을 논의해 보면 좋을 것 같습니다.

**Comment by DevLuce** [comment]
https://github.com/Integerous/goQuality-dev-contents
https://github.com/InSeong-So/IT-Note
https://github.com/vsouza/awesome-ios

1. 저도 문서 오픈소스에 기여한 경험이 없지만 이슈와 PR 템플릿이 잘 정돈된 3개의 문서 오픈소스 리포지토리를 위에 적어봤습니다. 깃허브에서 활발히 운영되고 있는 문서 오픈소스들을 참고하면 좋을것 같아요! :)
있으면 좋을 것 같은 이슈 템플릿은 일단 아래와 같이 생각해보았습니다.
   - 내용 수정/삭제 요청 : 불필요하거나 지원이 중단된 킷에 대한 문서 수정/삭제 요청 
   - 질문/건의 사항 : 문서에서 궁금하거나 프로젝트 내에 건의할 사항 공유
   - 컨텐츠 공유 : 문서보다는 이슈에서 공유되어야할 내용

2. 메인테이너는 원활한 문서관리와 이슈에 대한 즉각 반영을 위해 5-6명 정도는 필요하지 않을까합니다. 너무 많으면 책임이 분산되어 이슈와 PR 반영이 늦어질수도 있고...

3. 위의 세번째 리포지토리 awesome-ios 프로젝트에서 [CONTRIBUTING.md](https://github.com/vsouza/awesome-ios/blob/master/.github/CONTRIBUTING.md) 를 참고하면 좋을 것 같아요.
기존에 존재하는 내용인지, 애플에서 더 이상 지원하지 않지는 않는지 등에 대한 리뷰과정 이후에 PR이 필요할 것 같습니다.

4. Discussion, Project 기능을 써본적 없지만 본 프로젝트에서 활용해보면서 러너들이 배우는 기회를 가져보는 것이 좋을것 같다고 생각합니다. Discussion 을 잘 활용하고 있는 [프로젝트](https://github.com/tony9402/baekjoon)입니다.

이 프로젝트가 활발히 운영되어 지금의 아카데미, 앞으로의 아카데미 모든 러너에게 도움되는 문서로 거듭났으면 좋겠네요ㅎㅎ 좋은 프로젝트 생성해주셔서 감사합니다, 아이작! 이거 말고도 아카데미 내에 다양한 오픈소스 기여 문화가 생겼으면 합니다 :)

**Comment by DevKang** [comment]
@DevLuce 깔끔한 정리와 피드백 감사합니다 :) 5일전 코멘트를 이제야 보네요 ㅎㅎ 저 이외에 메인테이너가 필요하다는게 바로 증명이 되었군요 ㅎㅎ 혹시 이야기 나온 김에 첫번째 동료가 되어주실 수 있을까요? ㅎㅎ 확인하신다면 리버로 디엠 부탁드립니다 :)

**Comment by DevKang** [comment]
#3 을 통해서 이슈 템플릿 & 컨트리뷰션 가이드라인이 추가 되었습니다. 앞으로는 이 양식을 통해 활동 해주시길 바라며 이슈 마무리 하도록 하겠습니다~!
